import { Kanit, Inter, Lato } from 'next/font/google';
import "./globals.css";

// Import fonts
const kanit = Kanit({ subsets: ['latin'], weight: ['400', '700'] });
const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] });
const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className} >{children}</body>
    </html>
  );
}
