export const candidates = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    email: "john.doe@example.com",
    mobile: "1234567890",
    pincode: "123456",
    city: "New York",
    state: "New York",
    country: "USA",
    salary: "70",
    company: "TechCorp",
    position: "Software Engineer",
    tag: "Healthcare",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    mobile: "0987654321",
    pincode: "200002",
    city: "Los Angeles",
    state: "California",
    country: "India",
    salary: "85",
    company: "DesignPro",
    position: "UI/UX Designer",
    tag: "Healthcare",
  },
  {
    id: "3",
    firstName: "Robert",
    lastName: "Johnson",
    fullName: "Robert Johnson",
    email: "robert.johnson@example.com",
    mobile: "1122334455",
    pincode: "123456",
    city: "Chicago",
    state: "Illinois",
    country: "USA",
    salary: "90",
    company: "BizSolutions",
    position: "Project Manager",
    tag: "Healthcare",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Davis",
    fullName: "Emily Davis",
    email: "emily.davis@example.com",
    mobile: "2233445566",
    pincode: "111111",
    city: "Houston",
    state: "Texas",
    country: "India",
    salary: "75",
    company: "HealthPlus",
    position: "Data Analyst",
    tag: "Healthcare",
  },
  {
    id: "5",
    firstName: "Michael",
    lastName: "Wilson",
    fullName: "Michael Wilson",
    email: "michael.wilson@example.com",
    mobile: "3344556677",
    pincode: "500005",
    city: "Phoenix",
    state: "Arizona",
    country: "USA",
    salary: "80",
    company: "AutoTech",
    position: "Mechanical Engineer",
    tag: "Healthcare",
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Miller",
    fullName: "Sarah Miller",
    email: "sarah.miller@example.com",
    mobile: "4455667788",
    pincode: "111111",
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "India",
    salary: "68",
    company: "EduLearn",
    position: "Teacher",
    tag: "Healthcare",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Garcia",
    fullName: "David Garcia",
    email: "david.garcia@example.com",
    mobile: "5566778899",
    pincode: "700007",
    city: "San Antonio",
    state: "Texas",
    country: "USA",
    salary: "95",
    company: "FinServe",
    position: "Financial Analyst",
    tag: "Healthcare",
  },
  {
    id: "8",
    firstName: "Laura",
    lastName: "Martinez",
    fullName: "Laura Martinez",
    email: "laura.martinez@example.com",
    mobile: "6677889900",
    pincode: "800008",
    city: "San Diego",
    state: "California",
    country: "India",
    salary: "88",
    company: "CreativeWorks",
    position: "Graphic Designer",
    tag: "Healthcare",
  },
  {
    id: "9",
    firstName: "James",
    lastName: "Rodriguez",
    fullName: "James Rodriguez",
    email: "james.rodriguez@example.com",
    mobile: "7788990011",
    pincode: "111111",
    city: "Dallas",
    state: "Texas",
    country: "USA",
    salary: "82",
    company: "EnergyCorp",
    position: "Electrical Engineer",
    tag: "Healthcare",
  },
  {
    id: "10",
    firstName: "Sophia",
    lastName: "Hernandez",
    fullName: "Sophia Hernandez",
    email: "sophia.hernandez@example.com",
    mobile: "8899001122",
    pincode: "1000010",
    city: "San Jose",
    state: "California",
    country: "India",
    salary: "92",
    company: "GreenWorld",
    position: "Environmental Scientist",
    tag: "Healthcare",
  },
  {
    id: "11",
    firstName: "Daniel",
    lastName: "Lopez",
    fullName: "Daniel Lopez",
    email: "daniel.lopez@example.com",
    mobile: "9900112233",
    pincode: "1100011",
    city: "Austin",
    state: "Texas",
    country: "USA",
    salary: "78",
    company: "TechSolutions",
    position: "IT Support Specialist",
    tag: "Healthcare",
  },
  {
    id: "12",
    firstName: "Olivia",
    lastName: "Gonzalez",
    fullName: "Olivia Gonzalez",
    email: "olivia.gonzalez@example.com",
    mobile: "1112223344",
    pincode: "1200012",
    city: "Jacksonville",
    state: "Florida",
    country: "India",
    salary: "85",
    company: "MedHealth",
    position: "Nurse",
    tag: "Healthcare",
  },
];

export const cityData = ["Houston", "Dallas", "Chicago"];
export const stateData = ["New York", "Texas"];
export const salaryData = [
  "0 - 1 LPA",
  "2 - 5 LPA",
  "6 - 10 LPA",
  "11 - 15 LPA",
  "16 - 20 LPA",
  "21 - 25 LPA",
  "26 LPA & above",
];

export const tagData = [
  "Healthcare",
  "Car Owners",
  "Hospitality",
  "Third-party seller",
  "Finance",
  "Real Estate",
  "Car Seller",
  "Supplier",
];

export const industryData = [
  "Information Technology",
  "Consumer Goods",
  "Finance",
  "Media & Advertising",
  "Human Resources",
  "Pharmaceuticals",
  "Retail",
  "export construction",
];
export const jobPositionData = [
  "Senior Software Engineer",
  "Marketing Manager",
  "Senior Financial Analyst",
  "Lead Graphic Designer",
  "Civil Engineer",
  "HR Specialist",
  "Data Scientist",
  "Teacher",
  "Senior Product Manager",
];

export const companyData = ["ABC", "XYZ"];
export const pincodeData = ["123456", "111111"];
// export const contactData = ["ABC", "XYZ"];
export const countryData = ["India", "USA"];
